# Generated by Django 5.2.14 on 2026-06-17 02:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('glosa', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.PositiveIntegerField()),
                ('mes_cobro', models.DateField(help_text='Month being charged (use the 1st of the month).')),
                ('monto_cobro', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('moneda', models.CharField(choices=[('CLP', 'CLP'), ('UF', 'UF')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-mes_cobro', 'contract_id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_clp', models.DecimalField(decimal_places=2, help_text='Amount of the transfer applied to this charge, in CLP.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='tasks.bankmovement')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='tasks.collection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='payments',
            field=models.ManyToManyField(related_name='collections', through='tasks.PaymentAllocation', to='tasks.bankmovement'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('bank_movement', 'collection'), name='unique_movement_collection_allocation'),
        ),
    ]
